### PR TITLE
Fix code smells.

### PR DESCRIPTION
**Pull request by Fleshgrinder**
Simple fixes based on PhpStorm code inspection.

### CODE REVIEW

**Comment by bencorlett** [comment]
Unless I'm not privy to context here, that language in your description appears a little intimidating...

**Comment by Fleshgrinder** [comment]
That is not my intention (edited). I wanted to fix all of them, but some require a high amount of changes to the overall code structure and I think it is better to create issues for these cases.

**Comment by Fleshgrinder** [comment]
Please note that your code sniffer configuration actually reports some things that are valid according to the (not finished) PSR-5 and explicit return of null (which is a good thing, because it shows that you actually intended to return null and not return from a void method).

**Comment by nyamsprod** [comment]
@bencorlett  I understand what @Fleshgrinder was trying to say so I did not take it as an offense or anything :+1: . 

@Fleshgrinder About code fixer, I agree entirely I will update the configuration as I too think that return null **should** be explicit

**Pull request merged**
