### PR TITLE
Enhancement: Add Makefile with cs and test targets

### PR DESCRIPTION
**Pull request by localheinz**
This PR
- [x] adds a `Makefile` with `cs` and `test` targets
- [x] updates `CONTRIBUTING.md`
- [x] updates `README.md`

:information_desk_person: Since we're lazy, both targets depend on a `composer` target, which validates `composer.json` and `composer.lock`, as well as installs dependencies.

### CODE REVIEW

**Comment by nyamsprod** [comment]
@localheinz Since I'm not so much into makefile and all what is the big advantage of this over what I did with the [composer script](https://github.com/thephpleague/uri/blob/master/composer.json#L43) when I just need to type 

```
$ composer test
```

on the root directory of the package ?

**Comment by localheinz** [comment]
@nyamsprod 

Ha, cool, wasn't aware it was in there!

**Comment by nyamsprod** [comment]
I've documented it in the [README.md](https://github.com/thephpleague/uri#testing) to be more obvious :+1:

**Comment by localheinz** [comment]
:+1: Great job, @nyamsprod!

**Pull request closed without merging**
