### PR TITLE
Simplify The package Interfaces Usage

### PR DESCRIPTION
**Pull request by nyamsprod**
- Uri Modification Stage are now done using League Pipeline
  for simplicity

### CODE REVIEW

**Comment by nyamsprod** [comment]
The current PR will drastically simplify the code of league uri by removing overengineered classes and interfaces. 
- All schemes share a single Interface with one additional method in regard to PSR-7 UriInterface. 
- Modifiers are now classes that can modify URI object using their `__invoke` methods.
  The modifiers can also be grouped using the main class at the root of the package.
- Modifiers can be used on any URI object including PSR-7 compatible URI object

``` php
<?php

use League\Uri\Pipeline;
use League\Uri\Modifiers\AppendSegment;
use League\Uri\Modifiers\ReplaceLabel;
use League\Uri\Modifiers\Extension;
use League\Uri\Schemes\Http as HttpUri;

$uri = HttpUri::createFromString("http://www.example.com/report");
$extension_list = ['csv', 'json', 'xml'];
$links = [];

$common = (new Pipeline())
    ->pipe(new AppendSegment('/purchases/summary'))
    ->pipe(new ReplaceLabel(2, 'download'));
foreach ($extension_list as $extension) {
    $links[$extension] = $common->pipe(new Extension($extension))->__invoke($uri->withScheme('https'));
}

// $links is an array of League\Uri\Schemes\Http objects

echo $uri;           // display "http://www.example.com/report"
echo $links['csv'];  // display "https://download.example.com/report/purchases/summary.csv"
echo $links['xml'];  // display "https://download.example.com/report/purchases/summary.xml"
echo $links['json']; // display "https://download.example.com/report/purchases/summary.json"
```

@localheinz @Fleshgrinder The only real question is do we include the modifiers in this package or do we create a separate package for them ?

**Comment by Fleshgrinder** [comment]
Is the question still relevant for you? I was not online for quite some time and saw your mention of myself just today.

**Comment by nyamsprod** [comment]
@Fleshgrinder 
- The  src/Modifier.php class has been renamed src/Pipeline.php and will be remove/deprecated from the package as soon as league/pipeline hits version 1.0.
- After reading and thinking over your suggestion, the ArrayAccess interface is removed as accessing the URI component as arrays adds more "trouble" than benefits.
- I don't see the problem with having .idea added to the .gitignore. I don't usually use PHPStorm so adding it was a no brainier for me. I don't think adding it to the .gitignore degrade or harm the package in any way so I'll keep it

Last but not least, even if I merge the PR, you input is still valuable to me as I have taken into account your feedback :+1:

**Comment by Fleshgrinder** [comment]
The thing about the `.idea` folder is something I just wanted to mention; it does not harm anything! I used to put it in my `.gitignore`s for a long time until I was simply tired of it and added it to the global one.

Always glad if I am of help. :blush:

**Pull request merged**
