### PR TITLE
Add `toString` alias for `__toString`

### PR DESCRIPTION
**Pull request by ruudk**
## Introduction

We really love this library and started using it on some places in our application. 
### Describe the new/upated/fixed feature

It bugs me to see the `__toString()` everywhere. So I propose to create a nice alias called `toString`. It makes it a bit nicer, IMO.
### Backward Incompatible Changes

None
### Targeted release version

None
### PR Impact

Just a convenience alias

### CODE REVIEW

**Comment by nyamsprod** [comment]
@ruudk thanks for the kind words,

instead of using `toString` why not simply cast the object to a string with `(string) $uri` I mean that is the purpose of the `__toString` method ?

I don't get the added value of these kind of alias maybe a concrete example may help me understand the need for it ?

**Comment by ruudk** [comment]
I'd rather use nice flowing functions than casting it with `(string)`. But maybe that's just me?

**Comment by nyamsprod** [comment]
I still don't see the added value

**Comment by teohhanhui** [comment]
I think it'd be good if the documentation uses `(string) ...` cast everywhere instead of `->__toString()`.

**Comment by nyamsprod** [comment]
@teohhanhui Well `__toString` usage is documented on php documentation website why would the uri doc rehearsed was has already been explain for so long on php.net ?

**Comment by teohhanhui** [comment]
No, I mean the CS of our documentation. `(string) ...` cast is more natural.

**Pull request closed without merging**
